config/routes.rb
Rails.application.routes.draw do
 
  resources :guests
  get 'articles/votes'

  resources :comments
  get 'olds/result'

  resources :olds
  get 'articles/result'

  get 'articles/search'

  devise_for :users
 resources :articles

 resources :categories
 get 'categories/show'

 root "articles#index"
end

app/models/old.rb
class Old < ActiveRecord::Base
	def self.search(query)
  		where("articles_id = ?", "#{query}") 
	end
end

app/controllers/olds_controller.rb
class OldsController < ApplicationController
  before_action :set_old, only: [:show, :edit, :update, :destroy]

  # GET /olds
  # GET /olds.json
  def index
    @olds = Old.all
  end

  # GET /olds/1
  # GET /olds/1.json

  def result
    @clanci = Old.search(params[:format]).order("created_at DESC")
  end

  def show
  end

  # GET /olds/new
  def new
    @old = Old.new
  end

  # GET /olds/1/edit
  def edit
  end

  # POST /olds
  # POST /olds.json
  def create
    @old = Old.new(old_params)

    respond_to do |format|
      if @old.save
        format.html { redirect_to @old, notice: 'Old was successfully created.' }
        format.json { render :show, status: :created, location: @old }
      else
        format.html { render :new }
        format.json { render json: @old.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /olds/1
  # PATCH/PUT /olds/1.json
  def update
    respond_to do |format|
      if @old.update(old_params)
        format.html { redirect_to @old, notice: 'Old was successfully updated.' }
        format.json { render :show, status: :ok, location: @old }
      else
        format.html { render :edit }
        format.json { render json: @old.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /olds/1
  # DELETE /olds/1.json
  def destroy
    @old.destroy
    respond_to do |format|
      format.html { redirect_to olds_url, notice: 'Old was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_old
      @old = Old.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def old_params
      params.require(:old).permit(:articles_id, :title, :content, :created_at, :updated_at, :user_id, :category_id)
    end
end

app/helpers/olds_helper.rb
module OldsHelper
end

app/views/olds/_form.html.erb
<%= simple_form_for(@old) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <!--<%= f.input :articles_id %>-->
    <%= f.input :title %>
    <%= f.input :content %>
    <!--<%= f.input :created_at %>
    <%= f.input :updated_at %>
    <%= f.input :user_id %>
    <%= f.input :category_id %>-->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/olds/edit.html.erb
<h1>Editing Old</h1>

<%= render 'form' %>

<%= link_to 'Show', @old %> |
<%= link_to 'Back', olds_path %>

app/views/olds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Olds</h1>

<table>
 

  <tbody>
   <% @olds.each do |old| %>
  <h2><%= link_to old.title, old %></h2>
  <p>Published at <%= old.created_at.strftime('%b %d, %Y') %></p>
  <p><%= truncate(old.content, length: 200) %></p>
<% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Old', new_old_path %>

app/views/olds/new.html.erb
<h1>New Old</h1>

<%= render 'form' %>

<%= link_to 'Back', olds_path %>

app/views/olds/result.html.erb
<h1>Olds#result</h1>
<p>Find me in app/views/olds/result.html.erb</p>

<% @clanci.each do |version| %>
	<h2><%= link_to version.title, version %></h2>
	<p>Published at <%= version.created_at.strftime('%b %d, %Y') %></p>
	<p>Updated at <%= version.updated_at.strftime('%b %d, %Y') %></p>
	<p><%= truncate(version.content, length: 200) %></p>
<% end %>

app/views/olds/show.html.erb
div class="btn-group">
  <%= link_to "Back", root_path, class: "btn btn-default" %>
  <% if user_signed_in? %>
     <%= link_to "Edit", edit_old_path(@old), class: "btn btn-default" %>
     <%= link_to "Delete", old_path(@old), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
  <% end %>
</div>