config/routes.rb
Rails.application.routes.draw do
 
  resources :guests
  get 'articles/votes'

  resources :comments
  get 'olds/result'

  resources :olds
  get 'articles/result'

  get 'articles/search'

  devise_for :users
 resources :articles

 resources :categories
 get 'categories/show'

 root "articles#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    belongs_to :category

    def self.search(query)
  		where("title like ?", "%#{query}%") 
	end
	
	def self.search_category(query)
		where("category_id = ?", "#{query}")
	end
end

class ExampleSearch
  	include ActiveModel::Validations
  	include ActiveModel::Conversion
  	extend ActiveModel::Naming

  	attr_accessor :input

  	validates_presence_of :input
  	validates_length_of :input, :maximum => 50000

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        if params[:category].blank?
          @clanci = Article.all.order("created_at DESC")
        else
          @category_id = Category.find_by(name: params[:category]).id
          @clanci = Article.where(category_id: @category_id).order("created_at DESC")
          @subcategory = Category.search_owner(@category_id).order("name ASC")
        end
    end
    
    def result
        if params[:search]
            @clanci = Article.search(params[:search]).order("created_at DESC")
        else
            @clanci = Article.all.order('created_at DESC')
        end
    end 

    
    def show
        if params[:comment]
            Comment.create :content => params[:comment], :article_id => @article.id, :votes => 0
        end 
        @clanci =  Comment.search1(params[:id]).order("votes DESC")
    end
    
    def new
        @article = current_user.articles.build
    end
    
    def votes
        #aa
        @clanci =  Comment.search1(params[:article_id]).order("votes DESC")
        @clanci.each do |comment|
            if params[comment.content]=="yes"
                comment.update(:votes => comment.votes+1)
            end
        end
        @article = Article.find(params[:article_id])
        redirect_to @article
    end

    def create
        @article = current_user.articles.build(article_params)
        if @article.save
            flash[:success] = "Article Created successly!"
            redirect_to @article 
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        @clanci= Old.create :articles_id => @article.id, :title => @article.title, :content => @article.content, :user_id => @article.user_id, :category_id => @article.category_id, :created_at => @article.created_at, :updated_at => @article.updated_at
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article.destroy
        redirect_to root_path
    end
    
    private
    
    def find_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :content, :category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a Category" } %>
  <%= f.input :title %>
  <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  <%= tinymce %>
  <%= f.submit %>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>
<br>
<%= link_to "Back", root_path %>

app/views/articles/index.html.erb
<% if @subcategory!= nil%>	
	<h4>SubCategories</h4>
	<% @subcategory.each do |sub| %>
		<h2><%= link_to sub.name, articles_path(category: sub.name) %></h2>
	<% end %>
	<br>
<% end %>
<h4>Articles</h4>
<% @clanci.each do |article| %>
<div class="jumbotron">
		<h2><%= link_to article.title, article ,class: "list-group-item active"%></h2>
		<p>Published at <%= article.created_at.strftime('%b %d, %Y') %></p>
		<p><%= truncate(article.content.html_safe, length: 2000000) %></p>
		</div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>
<br>
<%= link_to "Back", root_path %>

app/views/articles/result.html.erb
<% @clanci.each do |article| %>
<div class="jumbotron">
		<h2><%= link_to article.title, article ,class: "list-group-item active"%></h2>
		<p>Published at <%= article.created_at.strftime('%b %d, %Y') %></p>
		<p><%= truncate(article.content.html_safe, length: 2000000) %></p>
		</div>
<% end %>

app/views/articles/search.html.erb
<%= form_tag( articles_result_path , :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/articles/show.html.erb
<div class="container-fluid">
 <div class="row">
   <div class=" col-md-2 nav navbar-nav navbar-right" align="right" style="padding-right:100px;">
    <%= render 'layouts/vote' %>
  </div>
  <div class="col-md-10 jumbotron">
   <h1><%= @article.title %></h1>
   <p><%= @article.content.html_safe %></p>
   <div class="btn-group">
    <%= link_to "Back", root_path, class: "btn btn-default" %>
    <% if user_signed_in? %>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-primary" %>
    <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <%= link_to "Old Version", olds_result_path(@article), class: "btn btn btn-info" %>
  </div>
</div>
</div>
<% end %>
</div>