config/routes.rb
Rails.application.routes.draw do
 
  resources :guests
  get 'articles/votes'

  resources :comments
  get 'olds/result'

  resources :olds
  get 'articles/result'

  get 'articles/search'

  devise_for :users
 resources :articles

 resources :categories
 get 'categories/show'

 root "articles#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer">

    <div id="left-footer">The <%= link_to "Wikipedia ", root_path %>by Tran Viet Hung, Nguyen Duy Hung, Nguyen Khac Khoi</a>
      <div>
    <div >
     <ul class="nav navbar-nav navbar-left" align="left">
   <li class="btn btn-social-icon btn-twitter">
    <a href="http://twitter.com", class="fa fa-twitter"></a>
   </li>
   <li class="btn btn-social-icon btn-facebook">
    <a href="http://facebook.com", class="fa fa-facebook"></a>     
    </li>
    <li class="btn btn-social-icon btn-google-plus"> 
   <a href="http://google.com", class="fa fa-google-plus"></a> 
</li>
</div>
</footer>

app/views/layouts/_searchbar.html.erb
<% if user_signed_in? %>
	<%= form_tag( articles_result_path , :method => "get", id: "search-form") do %>
  		<%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
  		<%= submit_tag "Search", :name => nil %>
	<% end %>
<% else %>
	<%= form_tag(  guests_path  , :method => "get", id: "search-form") do %>
  		<%= text_field_tag :search, params[:search], placeholder: "Search Articles", style:" background-color: white;
    background-image: url('searchicon.jpg');
    background-position: 10px 10px; 
    background-repeat: no-repeat;
    padding-left: 40px;
    border-radius: 4px;
    height : 30px;"

     %>
  		<%= submit_tag "Search", :name => nil, class: "btn btn-default", style:"
    background-color: #E8E8E8" %>
  	<% end %>
<% end %>

app/views/layouts/_vote.html.erb
<%= form_tag(article_path , :method => "get", id: "search-form") do %>
<%= text_field_tag :comment, params[:comment], placeholder: "Suggest", style:" background-color: white;
    background-position: 10px 10px; 
    background-repeat: no-repeat;
    padding-left: 40px;
    border-radius: 4px;
    height : 30px"%>
<%= hidden_field_tag(:article_id,@article.id) %>
<%= submit_tag "Suggest", :name => nil, class: "btn btn-default" , style:"
    background-color: #E8E8E8"%>
<% end %>

<%= form_tag( articles_votes_path , :method => "get", id: "vote-form") do %>
<% @clanci.each do |comment|%>
<p>
	<%= check_box_tag(comment.content,'yes')%>
	<%= comment.content %>
	<%= comment.votes %>
</p>
<% end %>
<%= hidden_field_tag(:article_id,@article.id) %>
<p><%= submit_tag "Vote", :name => nil, class: "btn btn-default",style:"
    background-color: #E8E8E8" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css" src="stylesheets/custom.css.scss"></style>
   <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
     <!-- Brand and toggle get grouped for better mobile display -->


     <%= link_to "Wikipedia", root_path, class: "navbar-brand" %>

     <div class="collapse navbar-collapse" id="navbar-collapsable">
      <ul class="nav navbar-nav ">
        <% if user_signed_in? %>
        <li><%= link_to "New Article", new_article_path %></li>
        <% end %>
        <li><%= render 'layouts/searchbar' =%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" align="right">
        <% if !user_signed_in? %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% else %>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>  
  </div>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container-fluid">
 <div class="row">
  <div class="col-md-2 navbar navbar-left" align="left">
    <ul class="list-group">
     <li class="list-group-item"><%= link_to "New Category", new_category_path %></li>
     <% Category.all.each do |category| %>
     <li class="list-group-item"><%= link_to category.name, articles_path(category: category.name) %></li>
     <% end %>
   </ul>
 </div>
  <div class="col-md-8">
  <%= yield %>
 </div>
   
</div>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
</div>
</body>
</html>